from __future__ import annotations

import json
import os
import plistlib
import re
import shlex
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

LABEL_PREFIX = "com.investment-engine"
LAUNCH_AGENTS_DIR = Path.home() / "Library" / "LaunchAgents"
SCRIPTS_DIR = Path.home() / "Library" / "Application Support" / "investment-engine"
LOGS_DIR = Path.home() / "Library" / "Logs"

NAME_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]{0,40}$")

Frequency = Literal["daily", "weekly", "monthly"]
CommandName = Literal["weekly", "analyze"]


@dataclass
class ScheduleSpec:
    name: str
    frequency: Frequency
    hour: int
    minute: int
    vault: Path
    command: CommandName = "weekly"
    weekday: int | None = None
    day: int | None = None
    tickers: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not NAME_PATTERN.match(self.name):
            raise ValueError(
                f"name {self.name!r} must match [a-z0-9][a-z0-9-]* and be <=41 chars"
            )
        if not (0 <= self.hour <= 23):
            raise ValueError(f"hour {self.hour} out of range [0,23]")
        if not (0 <= self.minute <= 59):
            raise ValueError(f"minute {self.minute} out of range [0,59]")
        if self.frequency == "weekly":
            if self.weekday is None or not (0 <= self.weekday <= 6):
                raise ValueError("weekly frequency requires weekday in [0,6] (0=Sun)")
        if self.frequency == "monthly":
            if self.day is None or not (1 <= self.day <= 31):
                raise ValueError("monthly frequency requires day in [1,31]")

    @property
    def label(self) -> str:
        return f"{LABEL_PREFIX}.{self.name}"


def plist_path(name: str) -> Path:
    return LAUNCH_AGENTS_DIR / f"{LABEL_PREFIX}.{name}.plist"


def script_path(name: str) -> Path:
    return SCRIPTS_DIR / f"{name}.sh"


def log_path(name: str) -> Path:
    return LOGS_DIR / f"investment-engine-{name}.log"


def build_calendar_interval(spec: ScheduleSpec) -> dict[str, int]:
    interval: dict[str, int] = {"Hour": spec.hour, "Minute": spec.minute}
    if spec.frequency == "weekly":
        assert spec.weekday is not None
        interval["Weekday"] = spec.weekday
    elif spec.frequency == "monthly":
        assert spec.day is not None
        interval["Day"] = spec.day
    return interval


def build_plist_bytes(spec: ScheduleSpec, script_file: Path) -> bytes:
    plist = {
        "Label": spec.label,
        "ProgramArguments": ["/bin/bash", str(script_file)],
        "StartCalendarInterval": build_calendar_interval(spec),
        "StandardOutPath": str(log_path(spec.name)),
        "StandardErrorPath": str(log_path(spec.name)),
        "RunAtLoad": False,
    }
    return plistlib.dumps(plist)


def build_wrapper_script(
    spec: ScheduleSpec,
    cli_path: str,
    tickers: list[str],
) -> str:
    vault = shlex.quote(str(spec.vault))
    cli = shlex.quote(cli_path)
    lines = [
        "#!/bin/bash",
        "# Generated by investment-engine schedule — do not edit by hand.",
        f"# Label: {spec.label}",
        "set -u",
        f"export PATH=\"{os.environ.get('PATH', '/usr/bin:/bin')}\"",
        "",
    ]
    for ticker in tickers:
        t = shlex.quote(ticker)
        lines.append(
            f'echo "[$(date -Iseconds)] running {spec.command} {ticker}"'
        )
        lines.append(
            f"{cli} {spec.command} {t} --vault {vault} || "
            f'echo "[warn] {ticker} failed"'
        )
    return "\n".join(lines) + "\n"


def tickers_from_registry(registry_path: Path) -> list[str]:
    return sorted(json.loads(Path(registry_path).read_text()).keys())


def install(
    spec: ScheduleSpec,
    cli_path: str,
    registry_path: Path,
) -> Path:
    LAUNCH_AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

    resolved_tickers = spec.tickers or tickers_from_registry(registry_path)
    if not resolved_tickers:
        raise ValueError("no tickers resolved (registry empty and none provided)")

    sp = script_path(spec.name)
    sp.write_text(build_wrapper_script(spec, cli_path, resolved_tickers))
    sp.chmod(0o755)

    pp = plist_path(spec.name)
    pp.write_bytes(build_plist_bytes(spec, sp))

    _launchctl_bootstrap(pp)
    return pp


def remove(name: str) -> tuple[bool, bool]:
    """Unload from launchd and delete plist + wrapper. Returns (plist_deleted, script_deleted)."""
    label = f"{LABEL_PREFIX}.{name}"
    _launchctl_bootout(label)

    pp = plist_path(name)
    plist_deleted = pp.exists()
    if plist_deleted:
        pp.unlink()

    sp = script_path(name)
    script_deleted = sp.exists()
    if script_deleted:
        sp.unlink()

    return plist_deleted, script_deleted


def list_jobs() -> list[dict]:
    if not LAUNCH_AGENTS_DIR.exists():
        return []
    jobs: list[dict] = []
    for pp in sorted(LAUNCH_AGENTS_DIR.glob(f"{LABEL_PREFIX}.*.plist")):
        try:
            with pp.open("rb") as f:
                data = plistlib.load(f)
        except Exception:
            continue
        label = str(data.get("Label", ""))
        name = label[len(LABEL_PREFIX) + 1 :] if label.startswith(LABEL_PREFIX + ".") else label
        jobs.append(
            {
                "name": name,
                "label": label,
                "plist": str(pp),
                "calendar": dict(data.get("StartCalendarInterval") or {}),
                "log": str(log_path(name)),
                "script": str(script_path(name)),
            }
        )
    return jobs


def _launchctl_bootstrap(plist_file: Path) -> None:
    uid = os.getuid()
    # If a job with the same label is already loaded, bootstrap fails.
    # Try a best-effort bootout first.
    try:
        with plist_file.open("rb") as f:
            data = plistlib.load(f)
        label = str(data.get("Label", ""))
        if label:
            subprocess.run(
                ["launchctl", "bootout", f"gui/{uid}/{label}"],
                check=False,
                capture_output=True,
                text=True,
            )
    except Exception:
        pass

    result = subprocess.run(
        ["launchctl", "bootstrap", f"gui/{uid}", str(plist_file)],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"launchctl bootstrap failed (exit {result.returncode}): "
            f"{result.stderr.strip() or result.stdout.strip()}"
        )


def _launchctl_bootout(label: str) -> None:
    uid = os.getuid()
    subprocess.run(
        ["launchctl", "bootout", f"gui/{uid}/{label}"],
        check=False,
        capture_output=True,
        text=True,
    )
